### ISSUE TITLE
Agenda - April 2016

### ISSUE THREAD

**Issue by bmf** [DockerHR/Logistics#1]
Sponsors:
IssueTrak - Space / Drinks
Agenda: Bret Fisher: Learn Docker Compose

**Comment by bmf** [comment]
Raw Git link to view the slides: http://rawgit.com/DockerHR/agendaSlides/master/april_2016.html

**Comment by bmf** [comment]
Docker Style guide: https://blog.docker.com/2013/06/announcing-new-docker-style/

**Comment by BretFisher** [comment]
Core docker colors: 
`#24b8eb  #2cf 
deepskyblue 
hsl(195,83,53) 
rgb(36,184,235)`
`#f0f0f0  #fff 
whitesmoke 
hsl(0,0,94) 
rgb(240,240,240)`
`#253237  #233 
darkslategray 
hsl(196,19,18) 
rgb(37,50,55)`

docker logos:
https://github.com/DockerHR/logos/tree/master/docker

**Comment by bmf** [comment]
Number of attendees ~10
Ordered 3 pizzas from Ray's NY Pizza
